### PR TITLE
Example: Task Planning app

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Task_planning_app
Login, sign up with fire_base authentication.

Each and every user have their own tasks or plans to do.
In this after user logged in he can see his plans if already present, if not he can plan or create his tasks, and he can update, he can also delete his tasks or plans after he done with his each task.

I had changed the package name to **github.nisrulz.todo_app**

once please check , kindly inform for any modifications hacktoberfest_23 : )

### CODE REVIEW

**Comment by nisrulz** [comment]
@Bharath-KumarReddy Thank you for your contribution. I will review it this week :)

**Comment by nisrulz** [comment]
@Bharath-KumarReddy if you can include a screenshot/video in your PR description it makes the PR more useful for review.

Also note how other contributors write their description. You will learn a lot as well as write better PR descriptions. Here is a PR #130  that you can use for reference and example, of how a good PR description looks like.

**Comment by nisrulz** [comment]
I have taken a quick look at your PR code @Bharath-KumarReddy . Take a look at my commit here: https://github.com/nisrulz/flutter-examples/commit/a9773768eb52b4882abfb78a5bb00d6c90d00f0c

**Comment by Bharath-KumarReddy** [comment]
here is the demo of firebase_todo_app [taskplanning]

https://github.com/nisrulz/flutter-examples/assets/127650446/fb42e860-3a32-43f3-bc29-18b9f226cc06

**Comment by Bharath-KumarReddy** [comment]
hi ,
any changes are  still needed , in order to merge this PR : )

**Comment by nisrulz** [comment]
@Bharath-KumarReddy yes. Please take a look at my last comment. I showcase changes needed in the PR.
1. The directory structure is not correct in your PR. I have changed that in the commit I mentioned above.
2. You need to cleanup your code a little bit.
3. you should not add google-services.json file as it has sensitive info about your Firebase instance and can be misused. Put a placeholder in place. Add instructions in readme for someone to set it up and replace placeholder json with the one the user has.
4. you should also bundle the iOS app, which is missing. You have macos, web and android.
5. Add a link in readme index to your app
6. Mention how to login into your app in readme. It can be hardcoded so it works everytime.

**Pull request closed without merging**
