### PR TITLE
Feature/firebase crash reporting

### PR DESCRIPTION
**Pull request by SAGARSURI**
Added Firebase Crashlytics demo app

### CODE REVIEW

**Comment by SAGARSURI** [comment]
@nisrulz Please review! 😄

**Comment by nisrulz** [comment]
I will get to your PR tomorrow @SAGARSURI

**Comment by SAGARSURI** [comment]
@nisrulz is there any update on this? :D

**Comment by nisrulz** [comment]
> @nisrulz is there any update on this? :D

I will definitely be getting to this after 14 Oct. Have too much stuff going on right now.

**Comment by SAGARSURI** [comment]
Any update on this?

**Pull request merged**
