### PR TITLE
Complete task_planning app

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Task Planning app.

Login, sign up with fire_base authentication.

Each and every user have their own tasks or plans to do.
In this after user logged in he can see his plans if already present, if not he can plan or create his tasks, and he can update, he can also delete his tasks or plans after he done with his each task.

Kindly assign a Label Hacktoberfest 

once please go though this and merge it , I am interested to contribute myself in hacktoberfest_23 : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
Once please go through this and merge it , kindly please say for further modifications hacktoberfest_23 : )

**Comment by Bharath-KumarReddy** [comment]
I had made a Task_planning app using flutter and Firebase as backend. 
Once go through this _hacktoberfest_23 : )

**Comment by nisrulz** [comment]
Can you explain to me what you did?

Why is there a `node_module` directory in this PR? This repo hosts flutter applications and not node web apps.

**Comment by Bharath-KumarReddy** [comment]
Node modules are present due to, 

Dart is the single language that  can be used to   for  web, Android , Ios etc .    Both web, Android, We can see the same results in both web, Android . 


But Okay, if node modules are not needed then I will delete the folder of web. 

I will go through the readme instructions : )

**Comment by nisrulz** [comment]
@Bharath-KumarReddy Thank you for clarifying. I know what it is used for. I was trying to hint why would you commit it to git repository. 

You need to add an entry in the gitignore file to not pull in all node modules. These files are supposed to be downloaded on the machine by whoever is wants to use them for. At times they are pulled from the shared repo in the system so they are not to be bundled with any repository that is pushed to Github.

I hope that clarifies everything for you.

**Comment by Bharath-KumarReddy** [comment]
hi ,
I resolved the issue of node_modules and I made a PR with commit message of **task_planning_app** ,
once please check and kindly inform in case of any modification   : )

**Pull request closed without merging**
