### PR TITLE
Task_planning_app  and Friday_virtual_assistant_app

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Task_planning_app
Login, sign up with fire_base authentication.

Each and every user have their own tasks or plans to do.
In this after user logged in he can see his plans if already present, if not he can plan or create his tasks, and he can update, he can also delete his tasks or plans after he done with his each task.

once please check , kindly inform for any modifications   hacktoberfest_23 : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
Friday_virtual_assistant,

User can speak and write his prompts same as that of chatgpt but here voice assistant is there to speek and listen to your questions and answer them all by providing the accurate content.

In this app, You can also get Images of your own imagination and you can also download them.

For example---
Astronaut riding a horse

This app is built using Flutter and OPENAI API.

once Please go through this , Kindly inform for any modification hacktoberfest_23 : )

**Comment by nisrulz** [comment]
@Bharath-KumarReddy 

Please open individual PR for each app separately. Do not bundle apps into the same PR, it is very hard to review with so many files (it shows 250 files in git diff right now).

Screenshot 2023-10-12 at 17 40 00

**Comment by nisrulz** [comment]
Additionally, I quickly noticed you are not following the rules mentioned in readme.

`namespace "com.example.todo_app"` this is wrong. This repository follows a standard package name for all examples apps to be consistent.

**Comment by Bharath-KumarReddy** [comment]
Thanking you for your patience ,
I will Open a new Individual PR 's  and 
I will the package name according to the app name as github.nisrulz.appname ;

**Pull request closed without merging**
