### PR TITLE
Added http dependency in pubspec.yaml

### PR DESCRIPTION
**Pull request by sanyamdogra**

### CODE REVIEW

**Comment by nisrulz** [comment]
@sanyamdogra Did you read about the guidelines before opening the [PR](https://github.com/nisrulz/flutter-examples#pull-requests)? 

Your target branch is set to master.

Also always provide description about the PR you are opening. If there was an existing issue, then tag it. If not the first open an issue and then open a PR against it.

**Comment by nisrulz** [comment]
@sanyamdogra I am only waiting on you changing the target branch. As soon as you do that, I will merge this PR. I do see the issue and for such a simple change, no need to open an issue. Simply change the target branch.

**Comment by nisrulz** [comment]
Related issue #16

**Comment by sanyamdogra** [comment]
I have changed the base branch as mentioned.

**Pull request merged**
