### PR TITLE
added example app using_slivers

### PR DESCRIPTION
**Pull request by rushikesh127001**
Hi sir, 
I have created an example app showing how to use Slivers Lists and Sliver Grids.
Please consider to merge if it seems helpful.
Thank You

### CODE REVIEW

**Comment by nisrulz** [comment]
Thank you for your contribution. I will take a look at this PR soon.

**Comment by rushikesh127001** [comment]
> Thank you for your contribution. I will take a look at this PR soon.

thank u ..hope it helps the project in a good way

**Comment by nisrulz** [comment]
I noticed you created a branch from master. You need to branch from `develop`, add your changes and then open a PR to `develop`.

**Comment by rushikesh127001** [comment]
Ok sure.will do that .but please can you not mark this pr as invalid? I am participating in hacktober fest for the first time and would be happy if I can get the t-shirt. So please don't mark this pr as invalid. Thank u

**Comment by nisrulz** [comment]
A PR that is not merged is anyways not counted for the Hacktoberfest. I am aware of the event that is on going. 🤷‍♂️

**Comment by nisrulz** [comment]
Closing since this PR is not valid anyways.

**Pull request closed without merging**
